# pytest configuration file
# pytest.ini
[pytest]
addopts = 
    -q
    --cov=src
    --cov-branch
    --cov-report=term-missing
    -p no:terminalprogress
testpaths = tests
python_files = test_*.py
pythonpath = src